version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /actions/setup-python
      - /actions/setup-node
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: build
      include: scope
